version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # üî• –î–ê–Å–ú –î–û–°–¢–£–ü –ö –î–û–ö–ï–†–£
    depends_on:
      - dind

  dind:
    image: docker:23.0-dind
    privileged: true
    container_name: dind
    environment:
      - DOCKER_TLS_CERTDIR=
    volumes:
      - docker_data:/var/lib/docker

volumes:
  jenkins_home:
  docker_data:
